# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('stock_number', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=126)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price_today_open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_yesterday_close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_now', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_today_max', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_today_min', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_deal_num', models.BigIntegerField()),
                ('stock_deal_money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock_buy_one_num', models.BigIntegerField()),
                ('stock_buy_one_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_buy_two_num', models.BigIntegerField()),
                ('stock_buy_two_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_buy_three_num', models.BigIntegerField()),
                ('stock_buy_three_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_buy_four_num', models.BigIntegerField()),
                ('stock_buy_four_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_buy_five_num', models.BigIntegerField()),
                ('stock_buy_five_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_sale_one_num', models.BigIntegerField()),
                ('stock_sale_one_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_sale_two_num', models.BigIntegerField()),
                ('stock_sale_two_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_sale_three_num', models.BigIntegerField()),
                ('stock_sale_three_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_sale_four_num', models.BigIntegerField()),
                ('stock_sale_four_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_sale_five_num', models.BigIntegerField()),
                ('stock_sale_five_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_date', models.CharField(max_length=10)),
                ('data_time', models.CharField(max_length=8)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
