# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtimestockdata',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtimestockdata',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
